/*
Terminal API

Terminal is a unified API that makes it easy to integrate with the leading telematics service providers.

Contact Support:
 Name: Terminal
 Email: connect@withterminal.com

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import { AxiosRequestConfig } from "axios";
import {
  AuthenticationApi,
  ConnectionsApi,
  DataManagementApi,
  DevicesApi,
  DriversApi,
  GroupsApi,
  HoursOfServiceApi,
  IFTAApi,
  IssuesApi,
  ProvidersApi,
  SafetyApi,
  TrailersApi,
  TripsApi,
  VehiclesApi,
} from "./api";
import { Configuration, ConfigurationParameters } from "./configuration";
import { TerminalCustom } from "./client-custom";

export class Terminal extends TerminalCustom {
  readonly authentication: AuthenticationApi;
  readonly connections: ConnectionsApi;
  readonly dataManagement: DataManagementApi;
  readonly devices: DevicesApi;
  readonly drivers: DriversApi;
  readonly groups: GroupsApi;
  readonly hoursOfService: HoursOfServiceApi;
  readonly iFTA: IFTAApi;
  readonly issues: IssuesApi;
  readonly providers: ProvidersApi;
  readonly safety: SafetyApi;
  readonly trailers: TrailersApi;
  readonly trips: TripsApi;
  readonly vehicles: VehiclesApi;

  constructor(configurationParameters: ConfigurationParameters) {
    super(configurationParameters);
    const configuration = new Configuration(configurationParameters);
    this.authentication = new AuthenticationApi(configuration);
    this.connections = new ConnectionsApi(configuration);
    this.dataManagement = new DataManagementApi(configuration);
    this.devices = new DevicesApi(configuration);
    this.drivers = new DriversApi(configuration);
    this.groups = new GroupsApi(configuration);
    this.hoursOfService = new HoursOfServiceApi(configuration);
    this.iFTA = new IFTAApi(configuration);
    this.issues = new IssuesApi(configuration);
    this.providers = new ProvidersApi(configuration);
    this.safety = new SafetyApi(configuration);
    this.trailers = new TrailersApi(configuration);
    this.trips = new TripsApi(configuration);
    this.vehicles = new VehiclesApi(configuration);
  }

}
