/* tslint:disable */
/* eslint-disable */
/*
Terminal API

Terminal is a unified API that makes it easy to integrate with the leading telematics service providers.

Contact Support:
 Name: Terminal
 Email: connect@withterminal.com

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, isBrowser } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { paginate } from "../pagination/paginate";
import type * as buffer from "buffer"
import { requestBeforeHook } from '../requestBeforeHook';
/**
 * DevicesApi - axios parameter creator
 * @export
 */
export const DevicesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * List all devices in the connected account.
         * @summary List Devices
         * @param {string} [cursor] Pagination cursor to start requests from
         * @param {string} [limit] The maximum number of results to return in a page.
         * @param {string} [modifiedAfter] Only include records that were last modified after a provided date.
         * @param {string} [modifiedBefore] Only include records that were last modified before a provided date.
         * @param {string} [raw] Include raw responses used to normalize model. Used for debugging or accessing unique properties that are not unified.
         * @param {string} [connectionToken] (Required) The token returned when a user authenticated their account. This authorizes access to a specific account.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllDevices: async (cursor?: string, limit?: string, modifiedAfter?: string, modifiedBefore?: string, raw?: string, connectionToken?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/devices`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)
            if (cursor !== undefined) {
                localVarQueryParameter['cursor'] = cursor;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (modifiedAfter !== undefined) {
                localVarQueryParameter['modifiedAfter'] = modifiedAfter;
            }

            if (modifiedBefore !== undefined) {
                localVarQueryParameter['modifiedBefore'] = modifiedBefore;
            }

            if (raw !== undefined) {
                localVarQueryParameter['raw'] = raw;
            }

            if (connectionToken != null) {
                localVarHeaderParameter['connection-token'] = String(connectionToken);
            }


    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/devices',
                httpMethod: 'GET'
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DevicesApi - functional programming interface
 * @export
 */
export const DevicesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DevicesApiAxiosParamCreator(configuration)
    return {
        /**
         * List all devices in the connected account.
         * @summary List Devices
         * @param {DevicesApiGetAllDevicesRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAllDevices(requestParameters: DevicesApiGetAllDevicesRequest = {}, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAllDevices(requestParameters.cursor, requestParameters.limit, requestParameters.modifiedAfter, requestParameters.modifiedBefore, requestParameters.raw, requestParameters.connectionToken, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * DevicesApi - factory interface
 * @export
 */
export const DevicesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DevicesApiFp(configuration)
    return {
        /**
         * List all devices in the connected account.
         * @summary List Devices
         * @param {DevicesApiGetAllDevicesRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllDevices(requestParameters: DevicesApiGetAllDevicesRequest = {}, options?: AxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.getAllDevices(requestParameters, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for getAllDevices operation in DevicesApi.
 * @export
 * @interface DevicesApiGetAllDevicesRequest
 */
export type DevicesApiGetAllDevicesRequest = {
    
    /**
    * Pagination cursor to start requests from
    * @type {string}
    * @memberof DevicesApiGetAllDevices
    */
    readonly cursor?: string
    
    /**
    * The maximum number of results to return in a page.
    * @type {string}
    * @memberof DevicesApiGetAllDevices
    */
    readonly limit?: string
    
    /**
    * Only include records that were last modified after a provided date.
    * @type {string}
    * @memberof DevicesApiGetAllDevices
    */
    readonly modifiedAfter?: string
    
    /**
    * Only include records that were last modified before a provided date.
    * @type {string}
    * @memberof DevicesApiGetAllDevices
    */
    readonly modifiedBefore?: string
    
    /**
    * Include raw responses used to normalize model. Used for debugging or accessing unique properties that are not unified.
    * @type {string}
    * @memberof DevicesApiGetAllDevices
    */
    readonly raw?: string
    
    /**
    * (Required) The token returned when a user authenticated their account. This authorizes access to a specific account.
    * @type {string}
    * @memberof DevicesApiGetAllDevices
    */
    readonly connectionToken?: string
    
}

/**
 * DevicesApiGenerated - object-oriented interface
 * @export
 * @class DevicesApiGenerated
 * @extends {BaseAPI}
 */
export class DevicesApiGenerated extends BaseAPI {
    /**
     * List all devices in the connected account.
     * @summary List Devices
     * @param {DevicesApiGetAllDevicesRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DevicesApiGenerated
     */
    public getAllDevices(requestParameters: DevicesApiGetAllDevicesRequest = {}, options?: AxiosRequestConfig) {
        return DevicesApiFp(this.configuration).getAllDevices(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }
}
