/* tslint:disable */
/* eslint-disable */
/*
Terminal API

Terminal is a unified API that makes it easy to integrate with the leading telematics service providers.

Contact Support:
 Name: Terminal
 Email: connect@withterminal.com

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, isBrowser } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { paginate } from "../pagination/paginate";
import type * as buffer from "buffer"
import { requestBeforeHook } from '../requestBeforeHook';
/**
 * SafetyApi - axios parameter creator
 * @export
 */
export const SafetyApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * List all safety events detected by the provider.
         * @summary List Safety Events
         * @param {string} [cursor] Pagination cursor to start requests from
         * @param {string} [limit] The maximum number of results to return in a page.
         * @param {string} [modifiedAfter] Only include records that were last modified after a provided date.
         * @param {string} [modifiedBefore] Only include records that were last modified before a provided date.
         * @param {string} [startedAfter] Only include records of statuses that started after a provided date.
         * @param {string} [startedBefore] Only include records of statuses that started before a provided date.
         * @param {string} [driverIds] Comma separated list of driver IDs to filter for
         * @param {string} [vehicleIds] Comma separated list of vehicle IDs to filter for
         * @param {string} [expand] Expand resources in the returned response
         * @param {string} [raw] Include raw responses used to normalize model. Used for debugging or accessing unique properties that are not unified.
         * @param {string} [connectionToken] (Required) The token returned when a user authenticated their account. This authorizes access to a specific account.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getEvents: async (cursor?: string, limit?: string, modifiedAfter?: string, modifiedBefore?: string, startedAfter?: string, startedBefore?: string, driverIds?: string, vehicleIds?: string, expand?: string, raw?: string, connectionToken?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/safety/events`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)
            if (cursor !== undefined) {
                localVarQueryParameter['cursor'] = cursor;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (modifiedAfter !== undefined) {
                localVarQueryParameter['modifiedAfter'] = modifiedAfter;
            }

            if (modifiedBefore !== undefined) {
                localVarQueryParameter['modifiedBefore'] = modifiedBefore;
            }

            if (startedAfter !== undefined) {
                localVarQueryParameter['startedAfter'] = startedAfter;
            }

            if (startedBefore !== undefined) {
                localVarQueryParameter['startedBefore'] = startedBefore;
            }

            if (driverIds !== undefined) {
                localVarQueryParameter['driverIds'] = driverIds;
            }

            if (vehicleIds !== undefined) {
                localVarQueryParameter['vehicleIds'] = vehicleIds;
            }

            if (expand !== undefined) {
                localVarQueryParameter['expand'] = expand;
            }

            if (raw !== undefined) {
                localVarQueryParameter['raw'] = raw;
            }

            if (connectionToken != null) {
                localVarHeaderParameter['connection-token'] = String(connectionToken);
            }


    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/safety/events',
                httpMethod: 'GET'
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * SafetyApi - functional programming interface
 * @export
 */
export const SafetyApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = SafetyApiAxiosParamCreator(configuration)
    return {
        /**
         * List all safety events detected by the provider.
         * @summary List Safety Events
         * @param {SafetyApiGetEventsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getEvents(requestParameters: SafetyApiGetEventsRequest = {}, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getEvents(requestParameters.cursor, requestParameters.limit, requestParameters.modifiedAfter, requestParameters.modifiedBefore, requestParameters.startedAfter, requestParameters.startedBefore, requestParameters.driverIds, requestParameters.vehicleIds, requestParameters.expand, requestParameters.raw, requestParameters.connectionToken, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * SafetyApi - factory interface
 * @export
 */
export const SafetyApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = SafetyApiFp(configuration)
    return {
        /**
         * List all safety events detected by the provider.
         * @summary List Safety Events
         * @param {SafetyApiGetEventsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getEvents(requestParameters: SafetyApiGetEventsRequest = {}, options?: AxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.getEvents(requestParameters, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for getEvents operation in SafetyApi.
 * @export
 * @interface SafetyApiGetEventsRequest
 */
export type SafetyApiGetEventsRequest = {
    
    /**
    * Pagination cursor to start requests from
    * @type {string}
    * @memberof SafetyApiGetEvents
    */
    readonly cursor?: string
    
    /**
    * The maximum number of results to return in a page.
    * @type {string}
    * @memberof SafetyApiGetEvents
    */
    readonly limit?: string
    
    /**
    * Only include records that were last modified after a provided date.
    * @type {string}
    * @memberof SafetyApiGetEvents
    */
    readonly modifiedAfter?: string
    
    /**
    * Only include records that were last modified before a provided date.
    * @type {string}
    * @memberof SafetyApiGetEvents
    */
    readonly modifiedBefore?: string
    
    /**
    * Only include records of statuses that started after a provided date.
    * @type {string}
    * @memberof SafetyApiGetEvents
    */
    readonly startedAfter?: string
    
    /**
    * Only include records of statuses that started before a provided date.
    * @type {string}
    * @memberof SafetyApiGetEvents
    */
    readonly startedBefore?: string
    
    /**
    * Comma separated list of driver IDs to filter for
    * @type {string}
    * @memberof SafetyApiGetEvents
    */
    readonly driverIds?: string
    
    /**
    * Comma separated list of vehicle IDs to filter for
    * @type {string}
    * @memberof SafetyApiGetEvents
    */
    readonly vehicleIds?: string
    
    /**
    * Expand resources in the returned response
    * @type {string}
    * @memberof SafetyApiGetEvents
    */
    readonly expand?: string
    
    /**
    * Include raw responses used to normalize model. Used for debugging or accessing unique properties that are not unified.
    * @type {string}
    * @memberof SafetyApiGetEvents
    */
    readonly raw?: string
    
    /**
    * (Required) The token returned when a user authenticated their account. This authorizes access to a specific account.
    * @type {string}
    * @memberof SafetyApiGetEvents
    */
    readonly connectionToken?: string
    
}

/**
 * SafetyApiGenerated - object-oriented interface
 * @export
 * @class SafetyApiGenerated
 * @extends {BaseAPI}
 */
export class SafetyApiGenerated extends BaseAPI {
    /**
     * List all safety events detected by the provider.
     * @summary List Safety Events
     * @param {SafetyApiGetEventsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SafetyApiGenerated
     */
    public getEvents(requestParameters: SafetyApiGetEventsRequest = {}, options?: AxiosRequestConfig) {
        return SafetyApiFp(this.configuration).getEvents(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }
}
