/*
Terminal API

Terminal is a unified API that makes it easy to integrate with the leading telematics service providers.

Contact Support:
 Name: Terminal
 Email: connect@withterminal.com

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface AuthenticationExchangeTokenRequest
 */
export interface AuthenticationExchangeTokenRequest {
    /**
     * 
     * @type {string}
     * @memberof AuthenticationExchangeTokenRequest
     */
    'publicToken'?: string;
}

