/*
Terminal API

Terminal is a unified API that makes it easy to integrate with the leading telematics service providers.

Contact Support:
 Name: Terminal
 Email: connect@withterminal.com

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ConnectionsUpdateCurrentConnectionDetailsRequestCompany } from './connections-update-current-connection-details-request-company';

/**
 * 
 * @export
 * @interface ConnectionsUpdateCurrentConnectionDetailsRequest
 */
export interface ConnectionsUpdateCurrentConnectionDetailsRequest {
    /**
     * 
     * @type {Array<string>}
     * @memberof ConnectionsUpdateCurrentConnectionDetailsRequest
     */
    'tags'?: Array<string>;
    /**
     * 
     * @type {ConnectionsUpdateCurrentConnectionDetailsRequestCompany}
     * @memberof ConnectionsUpdateCurrentConnectionDetailsRequest
     */
    'company'?: ConnectionsUpdateCurrentConnectionDetailsRequestCompany;
    /**
     * 
     * @type {string}
     * @memberof ConnectionsUpdateCurrentConnectionDetailsRequest
     */
    'externalId'?: string;
    /**
     * 
     * @type {string}
     * @memberof ConnectionsUpdateCurrentConnectionDetailsRequest
     */
    'status'?: string;
    /**
     * 
     * @type {string}
     * @memberof ConnectionsUpdateCurrentConnectionDetailsRequest
     */
    'syncMode'?: string;
}

