/*
Terminal API

Terminal is a unified API that makes it easy to integrate with the leading telematics service providers.

Contact Support:
 Name: Terminal
 Email: connect@withterminal.com

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ConnectionsCreateCustomConnectionRequestBackfill } from './connections-create-custom-connection-request-backfill';
import { ConnectionsCreateCustomConnectionRequestCompany } from './connections-create-custom-connection-request-company';
import { ConnectionsCreateCustomConnectionRequestCredentials } from './connections-create-custom-connection-request-credentials';

/**
 * 
 * @export
 * @interface ConnectionsCreateCustomConnectionRequest
 */
export interface ConnectionsCreateCustomConnectionRequest {
    /**
     * 
     * @type {Array<string>}
     * @memberof ConnectionsCreateCustomConnectionRequest
     */
    'tags'?: Array<string>;
    /**
     * 
     * @type {ConnectionsCreateCustomConnectionRequestBackfill}
     * @memberof ConnectionsCreateCustomConnectionRequest
     */
    'backfill'?: ConnectionsCreateCustomConnectionRequestBackfill;
    /**
     * 
     * @type {ConnectionsCreateCustomConnectionRequestCompany}
     * @memberof ConnectionsCreateCustomConnectionRequest
     */
    'company'?: ConnectionsCreateCustomConnectionRequestCompany;
    /**
     * 
     * @type {ConnectionsCreateCustomConnectionRequestCredentials}
     * @memberof ConnectionsCreateCustomConnectionRequest
     */
    'credentials'?: ConnectionsCreateCustomConnectionRequestCredentials;
    /**
     * 
     * @type {string}
     * @memberof ConnectionsCreateCustomConnectionRequest
     */
    'externalId'?: string;
    /**
     * 
     * @type {string}
     * @memberof ConnectionsCreateCustomConnectionRequest
     */
    'provider'?: string;
    /**
     * 
     * @type {string}
     * @memberof ConnectionsCreateCustomConnectionRequest
     */
    'syncMode'?: string;
}

